name: Merge main to development

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  merge-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --local user.email "actions@kalend.org"
          git config --local user.name "Github Actions"
          git config pull.rebase false
      - name: Merge main to development
        run: |
          git fetch --unshallow
          git checkout development
          git pull origin main
          git merge --no-ff main -m "Auto merge main to development"
          git push origin development
